# Generated by Django 5.0.2 on 2024-11-09 08:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='path/to/default/C:/Users/AGEBOBA CLINTON/Desktop/mv1.png', max_length=255, verbose_name='image'),
        ),
    ]
