# Generated by Django 5.0.2 on 2024-11-09 08:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0005_alter_comment_options_remove_post_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(default='path/to/default/https://res.cloudinary.com/dv21zubyl/image/upload/v1731135962/af6j0q3g6lzkp0tgto06.png', max_length=255, verbose_name='image'),
        ),
    ]
